import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import "animate.css";

import { DM_Sans } from "next/font/google";
import { register } from "swiper/element/bundle";
import MobailHeader1 from "@/components/layout/MobileHead";
import Footer from "@/components/layout/Footer";
register();
const DM_SansFont = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--dm-saans-font",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={DM_SansFont.variable}>
        <Header />
        <MobailHeader1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
